image: docker:git
services:
  - docker:dind

before_script:
  - docker login -u chinodesuuu -p $DOCKER_PASS

stages:
  - build
  - push

build_c9_v2:
  stage: build
  script:
    - docker build -t chinodesuuu/c9:v2 ./v2
build_c9_v3:
  stage: build
  script:
    - docker build -t chinodesuuu/c9:v3 ./v3
push_c9_v2:
  stage: push
  script:
    - docker push chinodesuuu/c9:v2
push_c9_v3:
  stage: push
  script:
    - docker push chinodesuuu/c9:v3
