version: 2
notify:
 webhooks:
   - url: https://claraio-circledisc.herokuapp.com/hooks/circleci
   
jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - run:
          name: Docker Build (Cloud9 V2)
          command: docker build -t chinodesuuu/c9:v2 -f v2.dockerfile .
      - run:
         name: Docker Build (AWS Cloud9 SDK (Previously Cloud9 V3 SDK))
         command: docker build -t chinodesuuu/c9:v3 -f v3.dockerfile .
                   
  deploy:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout     
      - run:
          name: Docker Build (Cloud9 V2)
          command: docker build -t chinodesuuu/c9:v2 -f v2.dockerfile .
      - run:
         name: Docker Build (AWS Cloud9 SDK (Previously Cloud9 V3 SDK))
         command: docker build -t chinodesuuu/c9:v3 -f v3.dockerfile .
      - run:
          name: Docker Push (Cloud9 V2)
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS && docker push chinodesuuu/c9:v2          
      - run:
          name: Docker Push (AWS Cloud9 SDK (Previously Cloud9 V3 SDK))
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS && docker push chinodesuuu/c9:v3          
                    

workflows:
  version: 2
  commit-workflow:
    jobs:
      - build
      - deploy:
          requires:
             - build
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master
    jobs:
      - build
      - deploy:
          requires:
             - build
  build-n-deploy: 
    jobs:
      - build
      - deploy:
          requires:
             - build
