version: 2
notify:
 webhooks:
   - url: https://claraio-circledisc.herokuapp.com/hooks/circleci
   
jobs:
  build:
    docker:
      - image: chinodesuuu/ci-amethyst:latest  
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.05.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Docker Build (Cloud9 V2)
          command: docker build -t chinodesuuu/c9:v2 ./v2
      - run:
         name: Docker Build (AWS Cloud9 SDK (Previously Cloud9 V3 SDK))
         command: docker build -t chinodesuuu/c9:v3 ./v3
                   
  deploy:
    docker:
      - image: chinodesuuu/ci-amethyst:latest
    steps:
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.05.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin      
      - run:
          name: Docker Build (Cloud9 V2)
          command: docker build -t chinodesuuu/c9:v2 ./v2
      - run:
         name: Docker Build (AWS Cloud9 SDK (Previously Cloud9 V3 SDK))
         command: docker build -t chinodesuuu/c9:v3 ./v3
      - run:
          name: Docker Push (Cloud9 V2)
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS && docker push chinodesuuu/c9:v2          
      - run:
          name: Docker Push (AWS Cloud9 SDK (Previously Cloud9 V3 SDK))
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS && docker push chinodesuuu/c9:v3          
                    

workflows:
  version: 2
  commit-workflow:
    jobs:
      - build
      - deploy:
          requires:
             - build
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0 0 0 * * 1"
          filters:
            branches:
              only: master
    jobs:
      - build
      - deploy:
          requires:
             - build
  build-n-deploy: 
    jobs:
      - build
      - deploy:
          requires:
             - build         
